### ISSUE TITLE
Grab icon path from PPD

### ISSUE THREAD

**Issue by rickheil** [nmcspadden/PrinterGenerator#25]
From @pexner on MacAdmins Slack #munki: 

A public request to anyone who can code and wants to add a very cool feature to PrinterGenerator: 
It seems possible to grab also the corresponding printer icon for munki!
It can be easily found inside the PPD used! Just search for `*APPrinterIconPath:`inside the PPD used. You'll see the /`path/to/the/printerXXX.icns` file.
I contaced Nick and he answered: _I have no plans to add that feature, but I welcome Pull Requests :slightly_smiling_face: I don't use this particular tool anymore and I have no spare time to work on it._
Is someone interested and able to make this possible, I'll pay in beer. (German beer, no sugar, no artificial flavours!)
Having the beautiful, corresponding printer icon in the optional installs would be cool.

**Comment by kevinmcox** [comment]
I've already got mine setup where I can specify the icon in the CSV and have it added to the pkginfo that is created, but the icon must already be in my Munki repo. This is convenient since we have a lot of the same model printers around.

Is @pexner thinking of a way to have it automatically copy the icon to the repo?

**Comment by nmcspadden** [comment]
It's a neat idea, but I have no plans to do this myself. I'll gladly accept PRs.

**Comment by rickheil** [comment]
@kevinmcox in my imagination, it would copy the icon with the same name as the printer so that it could be manually copied. I think copying into the icons folder in the repo is a lot of extra complication, especially since the script itself doesn't currently interact with the munki repo.

**Comment by kevinmcox** [comment]
@rickheil That makes since and is definitely less complicated.

But it does add a bunch of extra icons since there will be one for every single printer. I'm not sure if that really matters or not, but does create extra icons Munki has to download instead of just sharing one across multiple printers pkginfo files.

**Comment by pexner** [comment]
Yes, my idea was to keep it simple; it would extract the icon with the same name as the printer so that it could be manually copied to the repo.
Regarding @kevinmcox concern of too many icons: One pgkinfo has usually one icon. That's normal. Who has more than 100 printers? Even 100 icons don't take a lot of space. We're talking about the self-service printers. No user wants to browse 100 printers in Managed Software Centre. :)
